site_name: CSE314 Group Project
site_url: http://example.com/
nav:
    - Project Overview: index.md
    - Data Overview: data.md
    - preprocess demo code: preprocess.ipynb
    - eda: visualization.ipynb
    - feature: feature_selection.ipynb
    - Data Base: database.ipynb
    - Model1: modellogi.ipynb
    - Model2: modelrf.ipynb  
    - Model Examination: dash.ipynb
    - Kaggle Competition: Kaggle Competition.md

plugins:
  - mkdocs-jupyter

theme: readthedocs
